### ISSUE TITLE
Make modify quality image toolbar

### ISSUE THREAD

**Issue by percurnicus** [pbvarga1/pystamps#25]
Make a pop-up window from the toolbar to modify quality image flag. Use double line color over a white border to signify the quality flag and that it is selected

**Comment by godber** [comment]
This functionality implies communication with a specific database backend (e.g. the merweb website).  This is not the kind of thing we want to include directly into pystamps, but rather we want to facilitate some sort of modular way for people to extend `pystamps` to do.  Think of it this way, we could conceivably want to extend `pystamps` to set image quality for Mastcam images and Mastcam-Z images.

So this is multifold.  There must be a backend component, and interface between the backend defined, and it must somehow be modular or a plugin.  For instance we can't hardcode database or API URLs and username and passwords in the open source code.

**Comment by percurnicus** [comment]
Ok. Im going to close this issue.
