### ISSUE TITLE
I dislike how the pystamps method works

### ISSUE THREAD

**Issue by godber** [pbvarga1/pystamps#39]
In general I dislike how `pystamps` method works.  I think it should take a list of files, directories or globs as its primary argument.  It should loop over the elements of the list, test to see if the element is a directory, if so use it, if its a file, add it to the list of products and then last try and use it as a glob, add any products from that glob to the list of products.  I think this argument parser should actually be extracted into a function.

``` python
def pystamps(args=None):
    """Run pystamps from python shell or command line with arguments"""
    try:
        if len(args.file) > 1:
            files = args.file
        elif len(args.file) == 1:
            if os.path.isdir(args.file[0]):
                files = glob(os.path.join(str(args.file[0]), '*'))
            elif os.path.isfile(args.file[0]):
                files = glob(str(args.file[0]))
        else:
            files = glob('*')
    except AttributeError:
        if os.path.isdir(args):
            files = glob(os.path.join('%s' % (args), '*'))
        elif args:
            files = glob(args)
        else:
            files = glob('*')

    image_set = ImageSet(files)
    display = MainWindow(image_set.images)
    sys.exit(app.exec_())
```

**Comment by godber** [comment]
Also, I want to be able to run pystamps from the (i)python command line, something like this:

``` python
from pystamps import pystamps
pystamps("test/mission_data/")
pystamps("1p*img")
```

... and have the window come up.

I also want to do the following:

``` python
from pystamps import pystamps
pancam_images = pystamps("1p*img")
# select some images
assert pancam_images.selected == ["1p.....a.img", "1p.....b.img"]
```

**Comment by percurnicus** [comment]
So you want the ability to continue using the command line while the pystamps window is open?

**Comment by godber** [comment]
@pbvarga1 good question, that would be tricky and I hadn't really thought of it.  I don't think its strictly necessary, it can block while the window is up, but when it closes `pancam_images` gets set.

**Comment by percurnicus** [comment]
@godber Should ''selected'' only consist of just the basename or the entire relative path

**Comment by godber** [comment]
It seems like `pystamps` should maybe return an `ImageSet` which in turn should have a "property" that is a list of full paths to the `ImageStamp` products that are selected.  Does that make sense?

**Comment by godber** [comment]
Full or relative path, whatever was provided by the user.

**Comment by percurnicus** [comment]
yeah that makes sense

**Comment by percurnicus** [comment]
See https://github.com/pbvarga1/pystamps/commit/fda88c842c7da251d2d613a5731e3b01f3ebb111#diff-964484ed93b3a044233c755340f971a1L444

**Comment by godber** [comment]
Happier now
