### ISSUE TITLE
Make more user friendly

### ISSUE THREAD

**Issue by percurnicus** [pbvarga1/pystamps#5]

**Comment by pbvarga1** [comment]
See this example of a resize event:
* http://codeprogress.com/python/libraries/pyqt/showPyQTExample.php?index=360&key=QMainWindowResizeEvent

And documentation on resize events:
* https://srinikom.github.io/pyside-docs/PySide/QtGui/QResizeEvent.html
* http://srinikom.github.io/pyside-docs/PySide/QtGui/QWidget.html

**Comment by pbvarga1** [comment]
See if this can make clicking on the images easier:

* https://srinikom.github.io/pyside-docs/PySide/QtGui/QGraphicsScene.html#
* https://srinikom.github.io/pyside-docs/PySide/QtGui/QPainterPath.html#PySide.QtGui.QPainterPath
* https://srinikom.github.io/pyside-docs/PySide/QtCore/Qt.html [itemSelectionMode]

**Comment by pbvarga1** [comment]
And see if this can make things better:
http://www.pyqtgraph.org/documentation/index.html

**Comment by percurnicus** [comment]
- [x] Give each image a title with its name as the title. See http://doc.qt.io/qt-4.8/stylesheet-customizing.html#box-model and use math to set position, alter coloring of frame/border/margin if needed
- See if these make placing titles above the images easier:
  - `pos()` or `scenepos` https://srinikom.github.io/pyside-docs/PySide/QtGui/QGraphicsItem.html#PySide.QtGui.PySide.QtGui.QGraphicsItem
- [ ] fix underwrapping with for loop
- [x] while loop might fix too long of titles
- [ ] Use doubled line to potentially show that an image is selected and bad/good
- [x] Make scene change with mainwindow and wrap images with main window
- [x] Make items correct selectable when scroll bar present
- [x] Make lbl an attribute of ImageStamp within DisplayImages
- [x] Create global variables. 
- [x] Fix ambiguous variable names
- [x] Create Pystamps argument to place in user input path, send path to ImageSet. default to current directory
- [x] Clean up redundant/not needed lines.
- [x] Fix print_file() to print the absolute path of the file name
- [x] Insert some try statements to make things that shouldn't error not error
- [x] Fix values in mouse click so are based on screen size
- [x] Make scroll-able area

**Comment by pbvarga1** [comment]
Use these documentations

* https://srinikom.github.io/pyside-docs/PySide/QtGui/QGraphicsScene.html#PySide.QtGui.PySide.QtGui.QGraphicsScene.selectionChanged[selectedItems]
* https://srinikom.github.io/pyside-docs/PySide/QtGui/QGraphicsPixmapItem.html#qgraphicspixmapitem
* https://srinikom.github.io/pyside-docs/PySide/QtGui/QAbstractGraphicsShapeItem.html#qabstractgraphicsshapeitem
* Have the pixmap item inherit the the graphicsshapeitem, or visa versa if that doesn't work in order to set pen.
* https://srinikom.github.io/pyside-docs/PySide/QtGui/QGraphicsSimpleTextItem.html#PySide.QtGui.PySide.QtGui.QGraphicsSimpleTextItem.setText
  * Make a title for each image. See if you can inherit this as a parent and still set pen to make a border.

**Comment by percurnicus** [comment]
**Create invisible buttons**

_Create variable amount of buttons_
-  http://stackoverflow.com/questions/19156999/pyside-pyqt-getting-values-from-dynamically-created-qlineedits-on-button-clic

_Set Each button as a Graphics proxy button to place in Graphics Grid_
- https://srinikom.github.io/pyside-docs/PySide/QtGui/QGraphicsProxyWidget.html

_Resize Button to be the same size as picture and make transparent_
- https://srinikom.github.io/pyside-docs/PySide/QtGui/QWidget.html#PySide.QtGui.QWidget

_Or after making it a proxy widget_
- Resize
  -  https://srinikom.github.io/pyside-docs/PySide/QtGui/QGraphicsLayoutItem.html#PySide.QtGui.QGraphicsLayoutItem
- Set Palette (Transparent)
  - https://srinikom.github.io/pyside-docs/PySide/QtGui/QGraphicsWidget.html#PySide.QtGui.QGraphicsWidget
- See Other uses in code on setting palette
- https://srinikom.github.io/pyside-docs/PySide/QtGui/QPalette.html#PySide.QtGui.QPalette
- https://srinikom.github.io/pyside-docs/PySide/QtGui/QBrush.html#PySide.QtGui.QBrush
- https://srinikom.github.io/pyside-docs/PySide/QtCore/Qt.html
